<?php
//info con server
$URL = $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; //URI PARA VER RUTA COMPLETA
$NAME = $_SERVER['SCRIPT_NAME']; //SCRIPT QU SE ESTA EJECUTANDO
$PORT = $_SERVER["SERVER_PORT"]; //PUERTO QUE SE ESTA UTILIZANDO
$PROTOCOL = $_SERVER["SERVER_PROTOCOL"]; //PROTOCOLO HTTP

?>